### ISSUE TITLE
Allow transaction to execute "swap+pool deposit" and "pool withdraw+swap" in one call

### ISSUE THREAD

**Issue by 3esmit** [Uniswap/uniswap-v2-core#106]
Currently it's complicated to join or withdraw a pool at the right moment, unless user is using a smart contract wallet with custom logic.

To facilitate and reduce gas costs, add a secondary function which allows the swap ("correction of price") + deposit in pool, so the uniswap interface can be extended to allow user to correct the price of the pool to then deposit on the pool.

This procedure is even is even a requirement in the [docs](https://uniswap.org/docs/v2/core-concepts/pools/): `When other liquidity providers add to an existing pool, they must deposit pair tokens proportional to the current price. `
If the docs themselves suggest this, then the contract could and should allow this to happen in a single call. 

Users without smart contract wallets with custom code, cannot safely do this, because they are in risk of being front-runned while doing this two transaction operation, so is important that the contact provide this common use.

As a workaround for current pools contracts and router, a secondary contract, common to any pool, could do the two calls from one call, and the uni-swap interface can start using it.

See this discussion from last year, on reddit: https://www.reddit.com/r/UniSwap/comments/bf1g9q/how_to_mitigate_impermanent_loss/.

**Comment by moodysalem** [comment]
See https://github.com/Uniswap/uniswap-v2-periphery/pull/26

**Comment by moodysalem** [comment]
And https://github.com/Uniswap/uniswap-interface/issues/1079
