### ISSUE TITLE
Why uint32(block.timestamp % 2**32) ?

### ISSUE THREAD

**Issue by mudgen** [Uniswap/uniswap-v2-core#109]
The `update` function in UniswapV2Pair.sol [has this line of code](https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/UniswapV2Pair.sol#L75):
```Solidity
uint32 blockTimestamp = uint32(block.timestamp % 2**32);
```

In case of uint32 overflow the following return the same value:
```Solidity
uint32 blockTimestamp = uint32(block.timestamp % 2**32);
uint32 blockTimestamp = uint32(block.timestamp);
```

So why do this `block.timestamp % 2**32` ?   

It looks like the code is requiring the gas cost of doing a modulus operation for no reason.

Or is it done to show that overflow is okay?

**Comment by moodysalem** [comment]
You already reported this https://github.com/Uniswap/uniswap-v2-core/issues/96

**Comment by mudgen** [comment]
Oh, sorry, I didn't realize that.

**Comment by DEREK-DEV-AFK** [comment]
can you explain us ??

**Comment by DEREK-DEV-AFK** [comment]
can somebody explain why the value is not changing, even after `block.timestamp % 2**32` ?? i know it is use for overflow but how ?

**Comment by pradeepvarma22** [comment]
> can somebody explain why the value is not changing, even after `block.timestamp % 2**32` ?? i know it is use for overflow but how ?

This may help
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-September/018172.html

**Comment by Sufiyan-dev** [comment]
> > can somebody explain why the value is not changing, even after `block.timestamp % 2**32` ?? i know it is use for overflow but how ?
> 
> 
> 
> This may help
> 
> https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-September/018172.html

Thanks i got it
