### ISSUE TITLE
General Uniswap Questions

### ISSUE THREAD

**Issue by Colman** [Uniswap/uniswap-v2-core#112]
Hi I have a couple questions about Uniswap that I couldn't find answers to online.

1. When someone adds liquidity to a pool, what function gets called and in what contract file? I see functions for swapping but not for adding liquidity.

2. How is each person's share of liquidity tracked? Is it based on how many UNI tokens they redeem at the time of removing the liquidity or are UNI tokens different? Also what contract function is called to redeem their liquidity?

Thanks,
Colman

**Comment by dgczhh** [comment]
1. `mint`
2. `contract UniswapV2Pair is IUniswapV2Pair, UniswapV2ERC20`
3. `burn`

**Comment by moodysalem** [comment]
Think this discussion is better for the developers channel on the discord
https://discord.gg/jG5vpv
