### ISSUE TITLE
is:issue is:open I LAUNCHED UNI_V@ERC TWICE AND HAVE NOTHING I DID NOT MEAN TO DO IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! HELP????????????????????????

### ISSUE THREAD

**Issue by nmlm99** [Uniswap/uniswap-v2-core#120]
on rmeix it practiacllay forces you to hit the ercv2 button and it doubles it i lost 200 dollars can someone help

**Comment by nmlm99** [comment]
please

**Comment by moodysalem** [comment]
Not the right place for support, but I can tell you from your description there's nothing we can do
