### ISSUE TITLE
Reason about price accumulator when reserves go from >0 to 0

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-v2-core#19]

**Comment by moodysalem** [comment]
Just stumbled upon this. For posterity, this is no longer relevant (iiuc) reserves can never go to zero from above zero since we burn the first 1000 pool shares.

**Comment by xwvvvvwx** [comment]
Not sure if it's a concern in practice, but reserves can still go to zero if one of the underlying pool tokens deflates the pair's balances to zero, and then `sync` is called.
