### ISSUE TITLE
Keccak256 init code hash

### ISSUE THREAD

**Issue by 0xfourzerofour** [Uniswap/uniswap-v2-core#190]
I have taken the creation code from etherscan and tested it against the keccak256 hashing algorithm online.

The uniswapv2 documentation says that the computed hash should be 0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f

However when I put the creation code from etherscan into the function it gives me 9bb1c7971ee804c612ff67c797b1360aeb4174e9f16d29301553a62a799156b6

<img width="672" alt="Screen Shot 2023-03-08 at 10 25 01 pm" src="https://user-images.githubusercontent.com/36560907/223908719-eb6a8ca4-fe9c-4fac-a25d-d0003a5af635.png">

Do you know what I am doing wrong, I need this to work for a project of mine

**Comment by bencepalkovics** [comment]
Hey how did you solve this? I got the same as you
