### ISSUE TITLE
Publish compiler-input.json.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-v2-core#68]
In order for someone to verify Uniswap's code is legitimate, they need to run the same compiler with the same configuration and compare the output bytecode with the input bytecode.  Without publishing the compiler-input.json that was used to generate the build artifacts, a user cannot easily validate that the build artifacts were in fact generated from the source code in this repository.

Recommend publishing the compiler-input.json as part of the build artifacts so people can verify the build artifacts themselves.

**Comment by NoahZinsmeister** [comment]
is this the case? what necessary config information isn't already contained within the repo? i'm mostly thinking of the solc version from `package.json` and the config in `.waffle.json`.

**Comment by MicahZoltu** [comment]
At the moment I don't see any build scripts, so it is unclear what process you are going through to publish at all.  Even if I could derive everything from the repo, it would be *far* simpler to just copy a JSON string or file and feed it to solc than to try to create it by hand.  Presumably whatever build scripts you are using already generate this file, so it is just a matter of writing it to disk and committing it with the rest of the build artifacts.

**Comment by NoahZinsmeister** [comment]
i'm confused, `yarn` then `yarn compile` transparently generates the build artifacts.

**Comment by MicahZoltu** [comment]
Ah, I missed that you are using waffle (a tool I wasn't previously familiar with) to do builds, which is why you don't have any other build scripts in the repo.

I guess the pushback then is from the fact that you don't have access to the actual solc input.json as it is probably berried inside waffle?

As an auditor, it is much easier for me to audit the build process when I have a solc compiler input json because I can just plug it in to a previously audited compiler and see if it produces matching output.  With the current setup, I will have to either audit waffle to make sure it isn't doing anything untoward as part of the build process, or I will have to try to extract the input JSON from waffle myself, and then run that against a trusted copy of Solidity.

It is certainly possible to do either of these, just a pain.  ☺️

**Comment by NoahZinsmeister** [comment]
@MicahZoltu noted on all of this, one thing to keep in mind is that the testnet contracts did verify on etherscan, which is a reasonable indicator of correctness, though of course there's more we can do on this front.

**Comment by MicahZoltu** [comment]
How are you doing EtherScan verification if not via compiler-input?  Also, from a decentralized security standpoint, EtherScan can (and has been known to) fudge verification so probably shouldn't be relied on for "state actors" threat models.

**Comment by NoahZinsmeister** [comment]
> How are you doing EtherScan verification if not via compiler-input?

copy-pasting source code
