### ISSUE TITLE
price{0,1}CumulativeLast pair test is flaky

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-v2-core#72]
I think this probably has to do with the mineBlock method, or how the timestamps are moving in the underlying evm. 

I think we probably should just have a method on the contract that gets the current timestamp so we can override it for tests, per @MicahZoltu's suggestion. This is how I've always done it as well.

**Comment by MicahZoltu** [comment]
I saw this in my inbox 10 minutes after I finished figuring out how to mock the system clock in my docker containers... I still advocate for mockable timestamps, but I am now salty with my advocacy!

**Comment by MicahZoltu** [comment]
@moodysalem Re: `mineBlock` from ganache, this may be possibly related: https://github.com/trufflesuite/ganache-core/issues/509
