### ISSUE TITLE
Name all event parameters.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-v2-core#77]
https://github.com/Uniswap/uniswap-v2-core/blob/816075049f811f1b061bca81d5d040b96f4c07eb/contracts/UniswapV2Factory.sol#L13

The last parameter of this event is missing a name.  Either remove the parameter if it is meaningless, or give it a name so integrators know what it is.  The missing name also breaks my tooling, which makes me very sad.

**Comment by NoahZinsmeister** [comment]
the parameter is not meaningless, see https://uniswap.org/docs/v2/smart-contracts/factory/#paircreated, but it's not directly relevant for most people, so we've chosen not to name it. the contracts are frozen, so I'm afraid it's there to stay.
