### ISSUE TITLE
Issue on npm install 

### ISSUE THREAD

**Issue by aashipreet** [Uniswap/uniswap-v2-core#82]
https://documentcloud.adobe.com/link/track?uri=urn:aaid:scds:US:d0fbfdb8-7ccd-4e14-8072-994ddaeaa48a

I m not able to understand the exact problm. I have tried all possible solution but nothing worked so. The link shows the error I got.After setting all the environment variables path i m getting this error. I have to configure the msvs_version 2019 . Am basically trying to access the repo through running a server on different cmd.exe . For that i have installed the visual Studio Build tools. Please help.

**Comment by aashipreet** [comment]
Again when I tried in cmd:

> npm install -g windows-build-tools
I got:
https://documentcloud.adobe.com/link/track?uri=urn:aaid:scds:US:d0fbfdb8-7ccd-4e14-8072-994ddaeaa48a

**Comment by NoahZinsmeister** [comment]
i'm afraid we aren't able to offer debugging support, the code compiles and passes tests in CI, it should work locally with node@>=10 and yarn
