### ISSUE TITLE
HOT/ ETH Pair 

### ISSUE THREAD

**Issue by chasam501** [Uniswap/uniswap-v2-core#84]
Forgive me if not the place for this problem.  Added liquidity for the HOT/ ETH pair.  Added .5 Eth (~$112.00) and the $ equivalent HOT (~200,000 tokens).  Only 311 HOT taken from my wallet and .5 ETh was wrapped.  Now the pair shows $4.25 worth HOT (8100 tokens and $4.25 (0.019) worth of ETH in the POOL.    Not sure where the ETH went. 
Tx hash:   0xc2f22b5b46c3799926eeefbc28761761af9a8db7a0962c5076b01d4cc5a364e7     -     Thanks if you can help.

**Comment by moodysalem** [comment]
ask in the [discord](https://discord.com/invite/EwFs3Pp)
