### ISSUE TITLE
Errors encountered while doing operations to increase liquidity

### ISSUE THREAD

**Issue by Baker-Martin** [Uniswap/uniswap-v2-core#89]
When doing operations to increase liquidity, the ETH is deducted, but the CZZ token is not, and the txhash of the transaction is 0xdc8761b52200ccd40d4ac12dfd085a42a68f159beb7b77c24b0e909821e54c26

**Comment by moodysalem** [comment]
The pasted transaction is a simple send between two addresses

**Comment by Baker-Martin** [comment]
But this is the transaction sent after clicking the add button

**Comment by moodysalem** [comment]
I can assure you this transaction did not come from the Uniswap interface.

It's possible you were accessing a [phishing site](https://kb.myetherwallet.com/en/security-and-privacy/pro-tips-how-to-avoid-phishing-scams/). Please include the URL from where you accessed the add liquidity page.

**Comment by Baker-Martin** [comment]
Ok, Let me check. Thank you
