### ISSUE TITLE
yarn test failed

### ISSUE THREAD

**Issue by tolak** [Uniswap/uniswap-v2-core#95]
Hi, when i followed the README to test the code, i got the following errors after i issuing command "yarn test",:

![image](https://user-images.githubusercontent.com/16411474/91829437-0e63bb80-ec74-11ea-82d9-a34ea8703ead.png)

**Comment by hashparty1** [comment]
My system has some trouble building scrypt from the package. 
Try: `rm -rf node_modules && yarn add scrypt && yarn install && yarn test`
For some reason I think it builds a more compatible version that may be slightly different than what is in the package.json but all the tests seem to pass and I haven't encountered any other version compatibility issues yet.

**Comment by moodysalem** [comment]
Sometimes you have to yarn install twice because of scrypt failing the first time, won't be the case in future versions.

**Comment by HALF-XD** [comment]
> yarn install

你已经解决这个问题了吗？我现在也遇到这个问题，上面两个做法没有帮助，请问你是怎么解决的？
